### ISSUE TITLE
systemd docker container won't start after upgrading docker host to debian 11 :(

### ISSUE THREAD

**Issue by nyze88** [robertdebock/docker-debian-systemd#1]
Hi,

first of all: Thanks for your great work. This image is very useful for me :)

Since I upgraded my docker host to debian 11 I will get the following error if I want to start a container with systemd:

docker run \
  --tty \
  --privileged \
  --volume /sys/fs/cgroup:/sys/fs/cgroup:ro \
  robertdebock/debian
systemd 247.3-6 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified)
Detected virtualization docker.
Detected architecture x86-64.

Welcome to Debian GNU/Linux 11 (bullseye)!

Set hostname to <d640ccd57019>.
Failed to create /init.scope control group: Read-only file system
Failed to allocate manager object: Read-only file system
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...

If I remove the parameter --volume than I will get the following error:

docker run   --tty   --privileged   robertdebock/debian
Failed to mount cgroup at /sys/fs/cgroup/systemd: Operation not permitted
[!!!!!!] Failed to mount API filesystems.
Exiting PID 1...

Is it possible to fix it? Please help.

Thanks and have a nice day.

**Comment by robertdebock** [comment]
Hm, I don't have Debian 11, but please try this:

(`:ro` has been replaced by `:rw`, making `/sys/fs/cgroup` read-write.)

```
docker run
--tty
--privileged
--volume /sys/fs/cgroup:/sys/fs/cgroup:rw
robertdebock/debian
```

**Comment by gotmax23** [comment]
Hi @nyze88,

> Since I upgraded my docker host to debian 11 I will get the following error if I want to start a container with systemd:

I have had the same problem. It seems that Docker does not properly support running Systemd containers on systems using Cgroups V2. Debian 10 does not use Cgroups V2 but Debian 11 does. Here are two potential solutions:

1. Use Podman; this is what I do. It more secure than Docker due to its daemon-less architecture and ability to run rootless containers. More importantly, it has first-class support for running Systemd containers, even in rootless mode! You don't need to use `--privileged` or any other options that could compromise the security of your system; simply run `podman run robertdebock/debian` and it just works!
2. Disable Cgroups V2 using a kernel boot parameter and keep using Docker. While there might be another way to solve this issue, I haven't looked into it because I am satisfied with Podman.

> Hm, I don't have Debian 11, but please try this:
> 
> (`:ro` has been replaced by `:rw`, making `/sys/fs/cgroup` read-write.)
> 
> ```
> docker run
> --tty
> --privileged
> --volume /sys/fs/cgroup:/sys/fs/cgroup:rw
> robertdebock/debian
> ```

Either way, I am curious to know if changing `/sys/fs/cgroup:/sys/fs/cgroup:ro` to `/sys/fs/cgroup:/sys/fs/cgroup:rw` fixes the problem; I never tested this myself.

Good Luck,
Maxwell

**Comment by nyze88** [comment]
Hi,

sorry for my late response :-/

Thanks for the ideas.

I cannot use podman because I'm using the [mailcow](https://github.com/mailcow/mailcow-dockerized/) project for my mailserver which is using docker.

Finally I found a solution which is just a workaround to still use cgroups v1 but for me its ok :)

Link where I found the solution: https://serverfault.com/questions/1053187/systemd-fails-to-run-in-a-docker-container-when-using-cgroupv2-cgroupns-priva

At the end I can start the container as follows:

docker run \
--tty \
--privileged \
--volume /sys/fs/cgroup:/sys/fs/cgroup \
--cgroupns=host \
robertdebock/debian

**Comment by gotmax23** [comment]
Hi @nyze88,

> Finally I found a solution which is just a workaround to still use cgroups v1 but for me its ok :)
> 
> Link where I found the solution: https://serverfault.com/questions/1053187/systemd-fails-to-run-in-a-docker-container-when-using-cgroupv2-cgroupns-priva
> 
> At the end I can start the container as follows:
> 
> docker run
> --tty
> --privileged
> --volume /sys/fs/cgroup:/sys/fs/cgroup
> --cgroupns=host
> robertdebock/debian

I'm glad that you found a solution.

> I cannot use podman because I'm using the [mailcow](https://github.com/mailcow/mailcow-dockerized/) project for my mailserver which is using docker.

Just so you know, it is possible to run Docker and Podman side by side on the same system if you ever want to give it a try.

Thanks,
Maxwell
